version: '3.8'

services:
  discord-dashboard:
    build: .
    container_name: discord-dashboard
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
