# Production Docker-Compose für Discord Dashboard mit Registry Image
version: '3.8'

services:
  discord-dashboard:
    # Verwende Registry Image
    image: ghcr.io/bottrapper/discord-bot-dashboard:main
    container_name: discord-dashboard-prod
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3